# Generated by Django 5.1.7 on 2025-03-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
