# Generated by Django 5.1.7 on 2025-03-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0003_alter_contract_payment_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_timing',
            field=models.CharField(choices=[('none', 'None'), ('pickup', 'Payment at Pickup'), ('return', 'Payment at Return')], help_text='When payment is due', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_type',
            field=models.CharField(choices=[('none', 'None'), ('cash', 'Cash Payment'), ('charge', 'Charge Payment')], help_text='Type of payment accepted', max_length=10),
        ),
    ]
