# Generated by Django 5.1.7 on 2025-03-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0005_alter_contract_payment_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='return_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
