# Generated by Django 5.1.7 on 2025-03-19 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0006_alter_contract_return_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Format: +1234567890', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, help_text='Two-letter state code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, help_text='ZIP or postal code', max_length=10, null=True),
        ),
    ]
