# Generated by Django 5.1.7 on 2025-03-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0007_alter_customer_city_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='stored_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The rate that was calculated and stored when the contract was created', max_digits=10, null=True),
        ),
    ]
