# Generated by Django 5.1.7 on 2025-03-20 18:46

import rental_scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0008_contract_stored_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='drivers_license_number',
            field=models.CharField(blank=True, help_text="Customer's driver's license number", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='drivers_license_scan',
            field=models.FileField(blank=True, help_text="Scanned copy of driver's license", null=True, storage=rental_scheduler.models.AbsoluteFileSystemStorage(), upload_to=rental_scheduler.models.get_license_upload_path),
        ),
    ]
