# Generated by Django 5.1.7 on 2025-04-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0009_customer_drivers_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_network_path',
            field=models.BooleanField(default=False, help_text='Whether the license scan path is a network path'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='last_path_validation',
            field=models.DateTimeField(blank=True, help_text='When the license scan path was last validated', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='path_validation_error',
            field=models.TextField(blank=True, help_text='Error message if path validation failed', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='path_validation_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('checking', 'Checking'), ('error', 'Error')], default='checking', help_text='Current validation status of the license scan path', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_timing',
            field=models.CharField(choices=[('pickup', 'Payment at Pickup'), ('return', 'Payment at Return')], default='pickup', help_text='When payment is due', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('charge', 'Charge Payment')], default='cash', help_text='Type of payment accepted', max_length=10),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='hauling_capacity',
            field=models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in pounds', max_digits=10),
        ),
    ]
