# Generated by Django 5.1.7 on 2025-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0010_systemsettings_is_network_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='furniture_blanket_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of furniture blankets included in the rental'),
        ),
        migrations.AddField(
            model_name='contract',
            name='includes_evening_pickup',
            field=models.BooleanField(default=False, help_text='Whether this rental includes evening pickup'),
        ),
        migrations.AddField(
            model_name='contract',
            name='includes_hitch_bar',
            field=models.BooleanField(default=False, help_text='Whether this rental includes a hitch bar'),
        ),
        migrations.AddField(
            model_name='contract',
            name='strap_chain_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of straps/chains included in the rental'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='evening_pickup_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional charge for evening pickup', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='furniture_blanket_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price charged per furniture blanket', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hitch_bar_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price charged for hitch bar rental', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='strap_chain_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price charged per strap or chain', max_digits=10),
        ),
    ]
