# Generated by Django 5.1.7 on 2025-04-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0011_contract_furniture_blanket_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='furniture_blanket_quantity',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='includes_evening_pickup',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='strap_chain_quantity',
        ),
        migrations.AddField(
            model_name='contract',
            name='furniture_blanket_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of furniture blankets included'),
        ),
        migrations.AddField(
            model_name='contract',
            name='has_evening_pickup',
            field=models.BooleanField(default=False, help_text='Whether this rental includes evening pickup service'),
        ),
        migrations.AddField(
            model_name='contract',
            name='strap_chain_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of straps or chains included'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='evening_pickup_price',
            field=models.DecimalField(decimal_places=2, help_text='Price charged for evening pickup service', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='furniture_blanket_price',
            field=models.DecimalField(decimal_places=2, help_text='Price charged per furniture blanket', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='hitch_bar_price',
            field=models.DecimalField(decimal_places=2, help_text='Price charged for hitch bar rental', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='strap_chain_price',
            field=models.DecimalField(decimal_places=2, help_text='Price charged per strap or chain', max_digits=10),
        ),
    ]
