# Generated by Django 5.1.7 on 2025-07-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0014_remove_trailer_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(db_index=True, help_text='When the service period begins')),
                ('end_datetime', models.DateTimeField(db_index=True, help_text='When the service period ends')),
                ('description', models.CharField(blank=True, help_text='Description of the service being performed', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trailer', models.ForeignKey(help_text='Trailer being serviced', on_delete=django.db.models.deletion.CASCADE, to='rental_scheduler.trailer')),
            ],
            options={
                'verbose_name': 'Trailer Service',
                'verbose_name_plural': 'Trailer Services',
                'indexes': [models.Index(fields=['start_datetime'], name='rental_sche_start_d_2c1cc2_idx'), models.Index(fields=['end_datetime'], name='rental_sche_end_dat_42ef92_idx'), models.Index(fields=['trailer', 'start_datetime'], name='rental_sche_trailer_d064be_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='service_end_after_start')],
            },
        ),
    ]
