# Generated by Django 5.1.7 on 2025-07-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0015_trailerservice'),
    ]

    operations = [
        # Add indexes for commonly searched/filtered fields
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_trailer_number_search ON rental_scheduler_trailer (LOWER(number));",
            reverse_sql="DROP INDEX IF EXISTS idx_trailer_number_search;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_trailer_category_number ON rental_scheduler_trailer (category_id, number);",
            reverse_sql="DROP INDEX IF EXISTS idx_trailer_category_number;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_trailer_dimensions ON rental_scheduler_trailer (length, width);",
            reverse_sql="DROP INDEX IF EXISTS idx_trailer_dimensions;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_trailer_category_dimensions ON rental_scheduler_trailer (category_id, length, width);",
            reverse_sql="DROP INDEX IF EXISTS idx_trailer_category_dimensions;"
        ),
    ]
