# Generated by Django 5.2.5 on 2025-08-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0016_add_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_timing',
            field=models.CharField(choices=[('pickup', 'Payment at Pickup'), ('return', 'Payment at Return')], help_text='When payment is due', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('charge', 'Charge Payment')], help_text='Type of payment accepted', max_length=10),
        ),
    ]
