# Generated by Django 5.2.5 on 2025-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0017_alter_contract_payment_timing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_timing',
            field=models.CharField(choices=[('pickup', 'Payment at Pickup'), ('return', 'Payment at Return')], default='pickup', help_text='When payment is due', max_length=10),
        ),
    ]
