# Generated by Django 5.0.6 on 2025-08-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0018_remove_payment_type_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for the calendar (e.g., 'Shop', 'Mobile Unit A')", max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='CSS hex color code for calendar display (e.g., #3B82F6)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this calendar is active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'ordering': ['name'],
            },
        ),
    ]
