# Generated by Django 5.0.6 on 2025-08-27 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0019_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['business_name', 'contact_name']},
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Street address line 1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Street address line 2 (apartment, suite, etc.)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='alt_phone',
            field=models.CharField(blank=True, help_text='Alternative phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Format: +1234567890', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business or company name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, help_text="Primary contact person's name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the customer', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP or postal code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, help_text='Legacy field - use business_name or contact_name instead', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Format: +1234567890', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase order number (optional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_address',
            field=models.CharField(blank=True, help_text='Legacy field - use address_line1 instead', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Legacy field - use postal_code instead', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business_name'], name='rental_sche_busines_ded70b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['contact_name'], name='rental_sche_contact_01eda6_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='rental_sche_phone_59ed07_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='rental_sche_email_b0b16b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city'], name='rental_sche_city_e617de_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['state'], name='rental_sche_state_6967c7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business_name', 'contact_name'], name='rental_sche_busines_98f554_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone', 'alt_phone'], name='rental_sche_phone_443899_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city', 'state'], name='rental_sche_city_d0c84a_idx'),
        ),
    ]
