# Generated by Django 5.0.6 on 2025-08-27 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0021_add_invoice_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text="Unique name for the print template (e.g., 'invoice', 'work_order')", max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('invoice', 'Invoice'), ('work_order', 'Work Order'), ('quote', 'Quote'), ('receipt', 'Receipt')], help_text='Type of document this template is for', max_length=50)),
                ('company_name', models.CharField(blank=True, help_text='Company name to display on printed documents', max_length=200)),
                ('company_logo_path', models.CharField(blank=True, help_text='Path to company logo file (relative to media directory)', max_length=500)),
                ('company_address', models.TextField(blank=True, help_text='Company address to display on printed documents')),
                ('company_phone', models.CharField(blank=True, help_text='Company phone number to display on printed documents', max_length=20)),
                ('company_email', models.EmailField(blank=True, help_text='Company email to display on printed documents', max_length=254)),
                ('company_website', models.URLField(blank=True, help_text='Company website to display on printed documents')),
                ('header_color', models.CharField(default='#3B82F6', help_text='Header background color (CSS hex code)', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Main text color (CSS hex code)', max_length=7)),
                ('accent_color', models.CharField(default='#1F2937', help_text='Accent color for borders and highlights (CSS hex code)', max_length=7)),
                ('font_family', models.CharField(default='Arial, sans-serif', help_text='Font family for printed documents', max_length=100)),
                ('font_size', models.CharField(default='12px', help_text='Base font size for printed documents', max_length=20)),
                ('show_logo', models.BooleanField(default=True, help_text='Whether to show company logo on printed documents')),
                ('show_company_info', models.BooleanField(default=True, help_text='Whether to show company information on printed documents')),
                ('show_footer', models.BooleanField(default=True, help_text='Whether to show footer with additional information')),
                ('footer_text', models.TextField(blank=True, help_text='Custom footer text for printed documents')),
                ('default_tax_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Default tax rate for this template (e.g., 0.0825 for 8.25%)', max_digits=5)),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol to use on printed documents', max_length=5)),
                ('page_size', models.CharField(choices=[('letter', 'Letter (8.5" x 11")'), ('legal', 'Legal (8.5" x 14")'), ('a4', 'A4 (210mm x 297mm)')], default='letter', help_text='Page size for printed documents', max_length=20)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', help_text='Page orientation for printed documents', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_print_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_print_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Template Setting',
                'verbose_name_plural': 'Print Template Settings',
                'ordering': ['template_type', 'template_name'],
                'indexes': [models.Index(fields=['template_type'], name='rental_sche_templat_caf62b_idx'), models.Index(fields=['is_active'], name='rental_sche_is_acti_53d3f9_idx'), models.Index(fields=['template_name'], name='rental_sche_templat_90a385_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], help_text='Previous status of the job', max_length=20)),
                ('new_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], help_text='New status of the job', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the status change occurred')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the status change')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the status change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='Job that had its status changed', on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='rental_scheduler.job')),
            ],
            options={
                'verbose_name': 'Status Change',
                'verbose_name_plural': 'Status Changes',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['job', 'changed_at'], name='rental_sche_job_id_f617ce_idx'), models.Index(fields=['changed_by', 'changed_at'], name='rental_sche_changed_260de4_idx'), models.Index(fields=['new_status', 'changed_at'], name='rental_sche_new_sta_155b7e_idx')],
            },
        ),
    ]
