# Generated by Django 5.0.6 on 2025-09-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0022_add_audit_and_settings_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the job'),
        ),
        migrations.AddField(
            model_name='job',
            name='quote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quote amount for the job', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='trailer_color',
            field=models.CharField(blank=True, help_text='Color of the trailer', max_length=60),
        ),
        migrations.AddField(
            model_name='job',
            name='trailer_details',
            field=models.CharField(blank=True, help_text='Additional trailer details', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='trailer_serial',
            field=models.CharField(blank=True, help_text='Serial number of the trailer', max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name (overrides customer business name if different)', max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Contact person name (overrides customer contact name if different)', max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone (overrides customer phone if different)', max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='repeat_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='Type of repeat for recurring jobs', max_length=40),
        ),
    ]
