# Generated by Django 5.0.6 on 2025-09-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0023_job_notes_job_quote_job_trailer_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='repeat_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('monthly', 'Monthly'), ('yearly', 'Annually')], default='none', help_text='Type of repeat for recurring jobs', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('uncompleted', 'Uncompleted'), ('completed', 'Completed')], default='uncompleted', help_text='Current status of the job', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='new_status',
            field=models.CharField(choices=[('uncompleted', 'Uncompleted'), ('completed', 'Completed')], help_text='New status of the job', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='old_status',
            field=models.CharField(choices=[('uncompleted', 'Uncompleted'), ('completed', 'Completed')], help_text='Previous status of the job', max_length=20),
        ),
    ]
