# Generated by Django 5.0.6 on 2025-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0024_update_job_status_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='printtemplatesetting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='printtemplatesetting',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trailerservice',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='trailer',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='rental_sche_custome_82a1c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='rental_sche_trailer_84eb26_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Street address line 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Street address line 2 (apartment, suite, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business or company name', max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Contact person name', max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP or postal code', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, help_text='Two-letter state code', max_length=2),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='PrintTemplateSetting',
        ),
        migrations.DeleteModel(
            name='TrailerCategory',
        ),
        migrations.DeleteModel(
            name='TrailerService',
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
    ]
