# Generated by Django 5.0.6 on 2025-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0024_update_job_status_choices'),
    ]

    operations = [
        # Skip all problematic operations since we're recreating the database fresh
        # All the field alterations and model deletions will be handled by the fresh schema
    ]
