# Generated by Django 5.0.6 on 2025-10-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0029_fix_call_reminder_dates'),
        ('rental_scheduler', '0030_add_callreminder_model'),
    ]

    operations = [
    ]
