# Generated by Django 5.0.6 on 2025-10-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0031_merge_20251030_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='quote',
            field=models.CharField(blank=True, help_text='Quote amount or text for the job', max_length=100),
        ),
    ]










