# Generated by Django 5.0.6 on 2025-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0034_alter_job_quote_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='quote',
            field=models.CharField(blank=True, default='', help_text='Quote amount or text for the job', max_length=100),
        ),
    ]

