# Generated by Django 6.0 on 2025-12-18 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0035_alter_job_quote_add_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contract',
            name='rental_sche_start_d_4f3587_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='rental_sche_end_dat_55050e_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='rental_sche_is_pick_60c7d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='rental_sche_is_retu_87412a_idx',
        ),
        migrations.RemoveConstraint(
            model_name='contract',
            name='end_after_start',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_busines_ded70b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_contact_01eda6_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_phone_59ed07_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_email_b0b16b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_city_e617de_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_state_6967c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_busines_98f554_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_phone_443899_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='rental_sche_city_d0c84a_idx',
        ),
        migrations.RemoveIndex(
            model_name='printtemplatesetting',
            name='rental_sche_templat_caf62b_idx',
        ),
        migrations.RemoveIndex(
            model_name='printtemplatesetting',
            name='rental_sche_is_acti_53d3f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='printtemplatesetting',
            name='rental_sche_templat_90a385_idx',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveIndex(
            model_name='trailer',
            name='rental_sche_number_81a372_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailer',
            name='rental_sche_serial__b936cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailer',
            name='rental_sche_color_b5fc38_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailer',
            name='rental_sche_custome_8b5b20_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailer',
            name='rental_sche_is_avai_3e3cb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailer',
            name='rental_sche_is_rent_8124bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailer',
            name='rental_sche_categor_883928_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailer',
            name='rental_sche_custome_05bec9_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailerservice',
            name='rental_sche_start_d_2c1cc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailerservice',
            name='rental_sche_end_dat_42ef92_idx',
        ),
        migrations.RemoveIndex(
            model_name='trailerservice',
            name='rental_sche_trailer_d064be_idx',
        ),
        migrations.RemoveConstraint(
            model_name='trailerservice',
            name='service_end_after_start',
        ),
        migrations.AlterField(
            model_name='job',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Street address line 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Street address line 2 (apartment, suite, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business or company name', max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Contact person name', max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP or postal code', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='repeat_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Annually')], default='none', help_text='Type of repeat for recurring jobs', max_length=40),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, help_text='Two-letter state code', max_length=2),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uncompleted', 'Uncompleted'), ('completed', 'Completed'), ('canceled', 'Canceled')], help_text='New status of the job', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uncompleted', 'Uncompleted'), ('completed', 'Completed'), ('canceled', 'Canceled')], help_text='Previous status of the job', max_length=20),
        ),
        migrations.AddIndex(
            model_name='callreminder',
            index=models.Index(fields=['reminder_date'], name='callreminder_date_idx'),
        ),
        migrations.AddIndex(
            model_name='callreminder',
            index=models.Index(fields=['job'], name='callreminder_job_idx'),
        ),
        migrations.AddIndex(
            model_name='callreminder',
            index=models.Index(fields=['calendar', 'reminder_date'], name='callreminder_cal_date_idx'),
        ),
        migrations.AddIndex(
            model_name='callreminder',
            index=models.Index(condition=models.Q(('job__isnull', True)), fields=['calendar', 'reminder_date'], name='callreminder_standalone_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['start_dt', 'end_dt'], name='job_active_overlap_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['calendar', 'start_dt'], name='job_active_cal_start_idx'),
        ),
        migrations.RemoveField(
            model_name='printtemplatesetting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='printtemplatesetting',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='trailerservice',
            name='trailer',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='PrintTemplateSetting',
        ),
        migrations.DeleteModel(
            name='TrailerCategory',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Trailer',
        ),
        migrations.DeleteModel(
            name='TrailerService',
        ),
    ]
