# Generated by GPT-5.2 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_scheduler", "0038_add_calendar_feed_function"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderCompanyProfile",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("slogan", models.CharField(blank=True, default="", max_length=200)),
                ("address_line1", models.CharField(blank=True, default="", max_length=200)),
                ("address_line2", models.CharField(blank=True, default="", max_length=200)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=50)),
                ("zip", models.CharField(blank=True, default="", max_length=20)),
                ("tel", models.CharField(blank=True, default="", max_length=45)),
                ("fax", models.CharField(blank=True, default="", max_length=45)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Order Company Profile",
                "verbose_name_plural": "Work Order Company Profile",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Order Employee",
                "verbose_name_plural": "Work Order Employees",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderNumberSequence",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start_number", models.PositiveIntegerField(default=1)),
                ("next_number", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work Order Number Sequence",
                "verbose_name_plural": "Work Order Number Sequence",
            },
        ),
    ]

