# Generated by GPT-5.2 on 2026-01-27

import decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_scheduler", "0039_add_work_order_settings_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Auto-incrementing Work Order number (integer)",
                        unique=True,
                    ),
                ),
                (
                    "customer_org_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Classic Accounting customer org_id (nullable until selected)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("trailer_make_model", models.TextField(blank=True, default="")),
                ("trailer_color", models.CharField(blank=True, default="", max_length=100)),
                ("trailer_serial", models.CharField(blank=True, default="", max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("amount", "Amount ($)"), ("percent", "Percent (%)")],
                        default="amount",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        help_text="Associated job for this work order (v2)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order_v2",
                        to="rental_scheduler.job",
                    ),
                ),
                (
                    "job_by",
                    models.ForeignKey(
                        blank=True,
                        help_text='Employee who the job is "by" (nullable)',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders_v2",
                        to="rental_scheduler.workorderemployee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order (v2)",
                "verbose_name_plural": "Work Orders (v2)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderLineV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemid", models.PositiveIntegerField()),
                ("itemnumber_snapshot", models.CharField(blank=True, default="", max_length=60)),
                (
                    "description_snapshot",
                    models.CharField(blank=True, default="", max_length=3000),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("1.00"),
                        max_digits=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="rental_scheduler.workorderv2",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Line (v2)",
                "verbose_name_plural": "Work Order Lines (v2)",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="workorderlinev2",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty__gt", 0)),
                name="workorderlinev2_qty_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderlinev2",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)),
                name="workorderlinev2_price_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderlinev2",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="workorderlinev2_amount_gte_0",
            ),
        ),
    ]

