# Generated by Django 5.2.5 on 2026-02-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0041_workorderv2_tax_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrderCompanyProfile',
        ),
    ]
