# Generated by Django 6.0 on 2026-02-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0042_delete_workordercompanyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderv2',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
