# Generated by Django 6.0 on 2026-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0043_workorderv2_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderv2',
            name='accounting_invoice_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Link to AcctTrans.transid (Invoice) in Classic Accounting database', null=True),
        ),
    ]
