# Generated by Django 6.0 on 2026-02-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0044_workorderv2_accounting_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderv2',
            name='job_by',
        ),
        migrations.AddField(
            model_name='workorderv2',
            name='job_by_name',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the sales rep name at save time', max_length=60),
        ),
        migrations.AddField(
            model_name='workorderv2',
            name='job_by_rep_id',
            field=models.CharField(blank=True, default='', help_text='Classic Accounting Sales Rep UUID (from acct_sales_rep)', max_length=36),
        ),
    ]
