# Generated by Django 6.0 on 2026-02-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0045_replace_job_by_with_sales_rep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrderEmployee',
        ),
    ]
