# Generated by Django 6.0 on 2026-02-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0046_delete_workorderemployee'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='rental_sche_invoice_ae7d1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='rental_sche_invoice_60536f_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='rental_sche_job_id_1dc16c_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='rental_sche_work_or_014a61_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='rental_sche_is_dele_11f45d_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='rental_sche_created_f27e6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceline',
            name='rental_sche_invoice_f5f204_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceline',
            name='rental_sche_item_co_1f1553_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceline',
            name='rental_sche_created_4b3e60_idx',
        ),
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='invoice_line_positive_qty',
        ),
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='invoice_line_non_negative_price',
        ),
        migrations.RemoveConstraint(
            model_name='invoiceline',
            name='invoice_line_non_negative_total',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceLine',
        ),
    ]
