# Generated by Django 6.0 on 2026-02-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_scheduler', '0047_remove_invoice_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workorder',
            name='rental_sche_wo_numb_276885_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='rental_sche_wo_date_5c6729_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='rental_sche_job_id_d33bd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorderline',
            name='rental_sche_work_or_96a1ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorderline',
            name='rental_sche_item_co_b0de85_idx',
        ),
        migrations.RemoveIndex(
            model_name='workorderline',
            name='rental_sche_descrip_bbf6ca_idx',
        ),
        migrations.RemoveConstraint(
            model_name='workorderline',
            name='work_order_line_qty_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='workorderline',
            name='work_order_line_rate_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='workorderline',
            name='work_order_line_total_non_negative',
        ),
        migrations.RemoveField(
            model_name='workorderline',
            name='work_order',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.DeleteModel(
            name='WorkOrderLine',
        ),
    ]
