from django.urls import path
from .views import (
    SystemSettingsUpdateView, 
    HomeView,
    TrailerCategoryListView,
    TrailerCategoryCreateView,
    TrailerCategoryUpdateView,
    TrailerCategoryDeleteView,
    TrailerListView,
    TrailerCreateView,
    TrailerUpdateView,
    TrailerDeleteView,
    TrailerServiceCreateView,
    TrailerServiceManagementView,
    TrailerServiceUpdateView,
    TrailerServiceDeleteView,
    end_service_early,
    browse_folders,
    ContractListView,
    ContractDetailView,
    ContractCreateView,
    ContractUpdateView,
    ContractDeleteView,
    update_contract_status,
    contract_status_toggle,
    get_available_trailers,
    search_customers,
    CalendarView,
    get_calendar_data,
    get_job_calendar_data,
    update_job_status,
    get_calendar_legend,
    get_job_list_partial,
    update_job_status_quick,
    save_job_field,
    get_customer_info,
    get_trailer_info,
    add_work_order_line,
    update_work_order_line,
    delete_work_order_line,
    get_work_order_line_form,
    add_invoice_line,
    update_invoice_line,
    delete_invoice_line,
    get_invoice_line_form,
    InvoiceCreateFromWOView,
    InvoiceDetailView,
    InvoicePrintView,
    InvoiceUpdateView,
    InvoiceDeleteView,
    InvoiceListView,
    InvoiceLineCreateView,
    InvoiceLineUpdateView,
    InvoiceLineDeleteView,
    ContractPDFView,
    AvailabilityView,
    availability_search,
    test_404,
    test_500,
    test_403,
    test_400,
    validate_network_path,
    get_network_status,
    test_network_connection,
    CalendarListView,
    CalendarCreateView,
    CalendarUpdateView,
    CalendarDeleteView,
    JobListView,
    JobCreateView,
    JobDetailView,
    JobUpdateView,
    JobDeleteView,
    JobPrintWOView,
    JobPrintWOCustomerView,
    JobPrintInvoiceView,
    WorkOrderListView,
    WorkOrderCreateView,
    WorkOrderDetailView,
    WorkOrderUpdateView,
    WorkOrderDeleteView,
    WorkOrderLineCreateView,
    WorkOrderLineUpdateView,
    WorkOrderLineDeleteView,
    WorkOrderPrintView,
    WorkOrderCustomerPrintView,
    SearchView,
    search_results_partial,
    search_facet_counts,
    CalendarSettingsView,
    PrintTemplateSettingsView,
    update_calendar_color,
    toggle_calendar_active,
    update_print_template_setting,
    toggle_print_template_option,
    get_print_template_preview,
)
from .services.api_views import (
    calculate_rental_quote,
    get_calculation_constants,
    calculate_duration_info,
)
from . import error_views

app_name = 'rental_scheduler'

urlpatterns = [
    path('', CalendarView.as_view(), name='home'),
    path('settings/', SystemSettingsUpdateView.as_view(), name='settings_update'),
    path('availability/', AvailabilityView.as_view(), name='availability'),
    # Test error pages
    path('test/404/', test_404, name='test_404'),
    path('test/500/', test_500, name='test_500'),
    path('test/403/', test_403, name='test_403'),
    path('test/400/', test_400, name='test_400'),
    # Trailer Category URLs
    path('categories/', TrailerCategoryListView.as_view(), name='category_list'),
    path('categories/create/', TrailerCategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/edit/', TrailerCategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete/', TrailerCategoryDeleteView.as_view(), name='category_delete'),
    # Trailer URLs
    path('trailers/', TrailerListView.as_view(), name='trailer_list'),
    path('trailers/filter/', TrailerListView.as_view(), name='trailer_filter'),
    path('trailers/create/', TrailerCreateView.as_view(), name='trailer_create'),
    path('trailers/<int:pk>/edit/', TrailerUpdateView.as_view(), name='trailer_update'),
    path('trailers/<int:pk>/delete/', TrailerDeleteView.as_view(), name='trailer_delete'),
    # Trailer Service URLs
    path('trailers/<int:trailer_pk>/service/', TrailerServiceManagementView.as_view(), name='trailer_service_create'),
    path('trailers/<int:trailer_pk>/service/management/', TrailerServiceManagementView.as_view(), name='trailer_service_management'),
    path('trailers/<int:trailer_pk>/service/new/', TrailerServiceCreateView.as_view(), name='trailer_service_add'),
    path('service/<int:pk>/update/', TrailerServiceUpdateView.as_view(), name='trailer_service_update'),
    path('service/<int:pk>/delete/', TrailerServiceDeleteView.as_view(), name='trailer_service_delete'),
    path('service/<int:pk>/end-early/', end_service_early, name='end_service_early'),
    path('api/browse-folders/', browse_folders, name='browse_folders'),
    path('api/validate-network-path/', validate_network_path, name='validate_network_path'),
    path('api/test-network-connection/', test_network_connection, name='test_network_connection'),
    path('api/network-status/', get_network_status, name='get_network_status'),
    # Contract URLs
    path('contracts/', ContractListView.as_view(), name='contract_list'),
    path('contracts/<int:pk>/', ContractDetailView.as_view(), name='contract_detail'),
    path('contracts/create/', ContractCreateView.as_view(), name='contract_create'),
    path('contracts/<int:pk>/update/', ContractUpdateView.as_view(), name='contract_update'),
    path('contracts/<int:pk>/delete/', ContractDeleteView.as_view(), name='contract_delete'),
    path('contracts/<int:pk>/pdf/', ContractPDFView.as_view(), name='contract_pdf'),
    # Contract status endpoints
    path('contracts/<int:pk>/status/', contract_status_toggle, name='contract_status_toggle'),
    path('api/contracts/<int:pk>/update-status/', update_contract_status, name='update_contract_status'),
    path('api/contracts/get-available-trailers/', get_available_trailers, name='get_available_trailers'),
    # API endpoints
    path('api/search_customers/', search_customers, name='search_customers'),
    path('api/send-error-report/', error_views.send_error_report, name='send_error_report'),
    # Calculation API endpoints
    path('api/calculate-rental-quote/', calculate_rental_quote, name='calculate_rental_quote'),
    path('api/calculation-constants/', get_calculation_constants, name='get_calculation_constants'),
    path('api/calculate-duration/', calculate_duration_info, name='calculate_duration_info'),
    # Availability API endpoints
    path('api/availability/search/', availability_search, name='availability_search'),
    # Calendar URLs
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('api/calendar-data/', get_calendar_data, name='calendar_data'),
    path('api/job-calendar-data/', get_job_calendar_data, name='job_calendar_data'),
    path('api/jobs/<int:job_id>/update-status/', update_job_status, name='update_job_status'),
    path('api/calendar-legend/', get_calendar_legend, name='calendar_legend'),
    path('api/job-list-partial/', get_job_list_partial, name='job_list_partial'),
    path('api/jobs/<int:job_id>/update-status-quick/', update_job_status_quick, name='update_job_status_quick'),
    path('api/jobs/<int:job_id>/save-field/', save_job_field, name='save_job_field'),
    path('api/customers/<int:customer_id>/info/', get_customer_info, name='get_customer_info'),
    path('api/trailers/<int:trailer_id>/info/', get_trailer_info, name='get_trailer_info'),
    # Work Order Line Management
    path('api/workorders/<int:work_order_id>/add-line/', add_work_order_line, name='add_work_order_line'),
    path('api/workorderlines/<int:line_id>/update/', update_work_order_line, name='update_work_order_line'),
    path('api/workorderlines/<int:line_id>/delete/', delete_work_order_line, name='delete_work_order_line'),
    path('api/workorderlines/<int:line_id>/form/', get_work_order_line_form, name='get_work_order_line_form'),
    path('api/workorderlines/form/', get_work_order_line_form, name='get_work_order_line_form_new'),
    # Invoice Line Management
    path('api/invoices/<int:invoice_id>/add-line/', add_invoice_line, name='add_invoice_line'),
    path('api/invoicelines/<int:line_id>/update/', update_invoice_line, name='update_invoice_line'),
    path('api/invoicelines/<int:line_id>/delete/', delete_invoice_line, name='delete_invoice_line'),
    path('api/invoicelines/<int:line_id>/form/', get_invoice_line_form, name='get_invoice_line_form'),
    path('api/invoicelines/form/', get_invoice_line_form, name='get_invoice_line_form_new'),
    # Calendar Management URLs
    path('calendars/', CalendarListView.as_view(), name='calendar_list'),
    path('calendars/create/', CalendarCreateView.as_view(), name='calendar_create'),
    path('calendars/<int:pk>/edit/', CalendarUpdateView.as_view(), name='calendar_update'),
    path('calendars/<int:pk>/delete/', CalendarDeleteView.as_view(), name='calendar_delete'),
    # Job URLs
    path('jobs/', JobListView.as_view(), name='job_list'),
    path('jobs/create/', JobCreateView.as_view(), name='job_create'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job_detail'),
    path('jobs/<int:pk>/edit/', JobUpdateView.as_view(), name='job_update'),
    path('jobs/<int:pk>/delete/', JobDeleteView.as_view(), name='job_delete'),
    path('jobs/<int:pk>/print/wo/', JobPrintWOView.as_view(), name='job_print_wo'),
    path('jobs/<int:pk>/print/wo-customer/', JobPrintWOCustomerView.as_view(), name='job_print_wo_customer'),
    path('jobs/<int:pk>/print/invoice/', JobPrintInvoiceView.as_view(), name='job_print_invoice'),
    # Work Order URLs
    path('workorders/', WorkOrderListView.as_view(), name='workorder_list'),
    path('workorders/create/', WorkOrderCreateView.as_view(), name='workorder_create'),
    path('workorders/<int:pk>/', WorkOrderDetailView.as_view(), name='workorder_detail'),
    path('workorders/<int:pk>/edit/', WorkOrderUpdateView.as_view(), name='workorder_update'),
    path('workorders/<int:pk>/delete/', WorkOrderDeleteView.as_view(), name='workorder_delete'),
    path('workorders/<int:pk>/print/', WorkOrderPrintView.as_view(), name='workorder_print'),
    path('workorders/<int:pk>/print/customer/', WorkOrderCustomerPrintView.as_view(), name='workorder_customer_print'),
    # Work Order Line URLs
    path('workorderlines/create/', WorkOrderLineCreateView.as_view(), name='workorderline_create'),
    path('workorderlines/<int:pk>/edit/', WorkOrderLineUpdateView.as_view(), name='workorderline_update'),
    path('workorderlines/<int:pk>/delete/', WorkOrderLineDeleteView.as_view(), name='workorderline_delete'),
    
    # Invoice Management URLs
    path('invoices/', InvoiceListView.as_view(), name='invoice_list'),
    path('invoices/create-from-wo/<int:work_order_id>/', InvoiceCreateFromWOView.as_view(), name='invoice_create_from_wo'),
    path('invoices/<int:pk>/', InvoiceDetailView.as_view(), name='invoice_detail'),
    path('invoices/<int:pk>/print/', InvoicePrintView.as_view(), name='invoice_print'),
    path('invoices/<int:pk>/edit/', InvoiceUpdateView.as_view(), name='invoice_update'),
    path('invoices/<int:pk>/delete/', InvoiceDeleteView.as_view(), name='invoice_delete'),
    
    # Invoice Line Management URLs
    path('invoicelines/create/', InvoiceLineCreateView.as_view(), name='invoiceline_create'),
    path('invoicelines/<int:pk>/edit/', InvoiceLineUpdateView.as_view(), name='invoiceline_update'),
    path('invoicelines/<int:pk>/delete/', InvoiceLineDeleteView.as_view(), name='invoiceline_delete'),
    
    # Global Search URLs
    path('search/', SearchView.as_view(), name='search'),
    path('api/search/results/', search_results_partial, name='search_results_partial'),
    path('api/search/facet-counts/', search_facet_counts, name='search_facet_counts'),
    
    # Settings URLs
    path('settings/calendars/', CalendarSettingsView.as_view(), name='calendar_settings'),
    path('settings/print-templates/', PrintTemplateSettingsView.as_view(), name='print_template_settings'),
    path('api/calendars/<int:calendar_id>/update-color/', update_calendar_color, name='update_calendar_color'),
    path('api/calendars/<int:calendar_id>/toggle-active/', toggle_calendar_active, name='toggle_calendar_active'),
    path('api/print-templates/<int:template_id>/update-setting/', update_print_template_setting, name='update_print_template_setting'),
    path('api/print-templates/<int:template_id>/toggle-option/', toggle_print_template_option, name='toggle_print_template_option'),
    path('api/print-templates/<int:template_id>/preview/', get_print_template_preview, name='get_print_template_preview'),
]